const PATTERNS = [
  { name: "instruction-override", regex: /ignore\s+(all\s+)?previous\s+instructions/i },
  { name: "instruction-override", regex: /forget\s+(all\s+)?your\s+(rules|instructions|training)/i },
  { name: "role-hijack",          regex: /you\s+are\s+now\s+(?!claude)/i },
  { name: "role-hijack",          regex: /act\s+as\s+(?!a\s+helpful)/i },
  { name: "role-hijack",          regex: /pretend\s+(you\s+are|to\s+be)/i },
  { name: "system-spoof",         regex: /\[\s*SYSTEM\s*\]|\[\s*INST\s*\]/i },
  { name: "credential-theft",     regex: /(send|post|exfil|leak|print)\s+.*(api[_-]?key|token|secret|password|\.env)/i },
  { name: "destructive",          regex: /rm\s+-rf|delete\s+all|drop\s+table|format\s+(the\s+)?disk/i },
  { name: "obfuscated",           regex: /[A-Za-z0-9+/]{40,}={0,2}/ },
  { name: "hidden-html",          regex: /<!--[\s\S]*?(ignore|system|override|jailbreak)[\s\S]*?-->/i },
  { name: "jailbreak",            regex: /jailbreak|DAN\b|do\s+anything\s+now/i },
  { name: "zero-width",           regex: /[​-‍﻿⁠]/ },
];

// Whitelist: bekannte harmlose Muster die false positives erzeugen
const WHITELIST = [
  // IPFS CIDs (Qm... = CIDv0, bafy... = CIDv1)
  /^Qm[1-9A-HJ-NP-Za-km-z]{44,}$/,
  /^bafy[a-z2-7]{50,}$/,
  // SHA256 Hashes
  /^[a-f0-9]{64}$/,
  // npm package integrity hashes
  /^sha512-[A-Za-z0-9+/]+=*$/,
  // Git commit hashes
  /^[a-f0-9]{40}$/,
  // JWT tokens (header.payload.signature)
  /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/,
];

function isWhitelisted(match) {
  return WHITELIST.some(pattern => pattern.test(match.trim()));
}

function scan(text, source = "unknown") {
  const findings = [];
  for (const { name, regex } of PATTERNS) {
    const match = text.match(regex);
    if (match) {
      // Obfuscated-Pattern gegen Whitelist prüfen
      if (name === "obfuscated" && isWhitelisted(match[0])) {
        continue; // Bekanntes harmloses Muster — überspringen
      }
      findings.push({ type: name, match: match[0], index: match.index });
    }
  }
  return findings.length > 0
    ? { safe: false, source, findings }
    : { safe: true, source, findings: [] };
}

function scanRepo(dirPath) {
  const fs = require("fs");
  const path = require("path");
  const results = [];

  function walk(dir) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (["node_modules", ".git", "dist", ".cache"].includes(entry.name)) continue;
        walk(fullPath);
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if ([".md", ".txt", ".js", ".ts", ".json", ".yaml", ".yml", ".sh"].includes(ext)) {
          try {
            const text = fs.readFileSync(fullPath, "utf8");
            const result = scan(text, fullPath);
            results.push(result);
          } catch (_) {}
        }
      }
    }
  }

  walk(dirPath);
  return results;
}

function generateReport(results, format = "markdown") {
  const safe = results.filter(r => r.safe);
  const threats = results.filter(r => !r.safe);
  const timestamp = new Date().toISOString();

  if (format === "json") {
    return JSON.stringify({ timestamp, summary: { total: results.length, safe: safe.length, threats: threats.length }, threats }, null, 2);
  }

  // Markdown report
  let report = `# 🛡️ Venom Shield Scan Report\n\n`;
  report += `**Date:** ${timestamp}\n`;
  report += `**Files scanned:** ${results.length}\n`;
  report += `**Safe:** ${safe.length} ✅\n`;
  report += `**Threats found:** ${threats.length} ${threats.length > 0 ? "⚠️" : "✅"}\n\n`;

  if (threats.length === 0) {
    report += `## ✅ All Clear — No injection patterns detected.\n`;
  } else {
    report += `## ⚠️ Threats Detected\n\n`;
    for (const t of threats) {
      report += `### \`${t.source}\`\n`;
      for (const f of t.findings) {
        report += `- **Type:** ${f.type}\n`;
        report += `  **Match:** \`${f.match.substring(0, 80)}\`\n`;
        report += `  **Offset:** ${f.index}\n\n`;
      }
    }
  }

  report += `---\n*Generated by [Venom Shield](https://github.com/Sa1bou/venom-shield)*\n`;
  return report;
}

module.exports = { scan, scanRepo, generateReport, PATTERNS, WHITELIST };
